apiVersion: v1
kind: Namespace
metadata:
  name: dev-x
  labels:
    app: kube-wild-manualtest
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-a
  labels:
    app: kube-wild-manualtest
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-b
  labels:
    app: kube-wild-manualtest
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-alexv-test
  labels:
    app: kube-wild-manualtest
