apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: dev-x
  labels:
    app: kube-wild-manualtest
spec:
  selector:
    app: api-1
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: dev-x
  labels:
    app: kube-wild-manualtest
spec:
  selector:
    app: web-1
  ports:
    - port: 80
      targetPort: 80
