name: krew-release-bot

on:
  # If a release is created manually, still run
  release:
    types: [published]
  # Allow manual runs from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish to krew-index (e.g., v0.0.5)"
        required: true

jobs:
  krew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rajatjindal/krew-release-bot@v0.0.46
        with:
          workdir: .
          krew-template-file: .krew.yaml
        env:
          # Prefer PAT if provided; fallback to default token
          GITHUB_TOKEN: ${{ secrets.KREW_RELEASE_BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          # The bot requires GITHUB_REF to be refs/tags/<tag>
          GITHUB_REF: ${{ github.event_name == 'release' && format('refs/tags/{0}', github.event.release.tag_name) || format('refs/tags/{0}', inputs.tag) }}
