name: krew-release-bot

on:
  # If a release is created manually, still run
  release:
    types: [published]
  # When our "release" workflow (that uploads assets) completes, run the bot.
  workflow_run:
    workflows: ["release"]
    types: ["completed"]

jobs:
  krew:
    runs-on: ubuntu-latest
    steps:
      - uses: rajatjindal/krew-release-bot@v0.0.46
